In [ ]:
idades = [30,25,41,18] #criar listas
print(idades) #primeiro indice é zero

salarios = [500, 600, 800, 700]
salarios [2] = 900 #800 vira 900
print(salarios)
print(salarios[2])
salarios[0] = salarios[1] #atribuindo valores por lista
print(salarios)

tamanho = len(salarios) #tamanho lista
print(tamanho)

[30, 25, 41, 18]
[500, 600, 900, 700]
900
[600, 600, 900, 700]
4

In [ ]:
nomes = ["Matheus", "Lucas", "Tiago", "João"]
salarios = [500, 600, 800, 700]
total = 0

for i in range (0,4):
  print(i+1, nomes[i]) #i+1 pois zero é feio

print("--")

for i in range (0,len(nomes)):
  print(i, nomes[i]) 

print("--")

for i in nomes:
  print(i) #i+1 pois zero é feio

print("--")

for x in salarios:
  total = total + x
print(total)

contem = "Lucas" in nomes #search em listas
print(contem)
if contem:
  k = nomes.index("Lucas")# localiza o objeto
  nomes[k] = "arroz"
  print(nomes[k])

if nomes.index("arroz"):
  k = nomes.index("arroz")# localiza o objeto
  nomes[k] = "Lucas"
  print(nomes[k])

nomes.insert(2, "Pedro")
print(nomes)

nomes.append("Pedro")
print(nomes)

del nomes[2]
print(nomes)

nomes.sort(reverse=False)
print(nomes)

nomes.sort(reverse=True)
print(nomes)

print(max(salarios))
print(min(salarios))

1 Matheus
2 Lucas
3 Tiago
4 João
--
0 Matheus
1 Lucas
2 Tiago
3 João
--
Matheus
Lucas
Tiago
João
--
2600
True
arroz
Lucas
['Matheus', 'Lucas', 'Pedro', 'Tiago', 'João']
['Matheus', 'Lucas', 'Pedro', 'Tiago', 'João', 'Pedro']
['Matheus', 'Lucas', 'Tiago', 'João', 'Pedro']
['João', 'Lucas', 'Matheus', 'Pedro', 'Tiago']
['Tiago', 'Pedro', 'Matheus', 'Lucas', 'João']
800
500

In [ ]:
#tuplas ao inves de [] agr é ()
dias = ("segunda","terça","quarta","quinta","sexta","sabado","domingo")
print(dias)
#não aplica insert, sort, del ou coisas do genero
k = dias.index("segunda")
print(k)

print(min(dias))
print(max(dias))

('segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo')
0
domingo
terça

In [ ]:
import math #exercicios

X = [] #definindo listas
Y = []
pi = math.pi

n = int(input(print("Insira o número de vezes a ser calculado")))

for i in range(0,n): # for 
  x = float(input(print("Insira o", i+1,+"º valor:")))
  X.append(x)

X.sort(reverse=False)

for i in range(0,n):
  y = X[i]
  gy = math.log2(y)+((math.pow(pi,3))/(2*math.exp(y)))
  Y.append(gy)

Y.sort(reverse=False)

for i in range(len(Y)):
    print("x:",round(X[i],4),"y:",round(Y[i],4))

Insira o número de vezes a ser calculado
1
Insira o 1 º valor:
1.1234566
x: 1.1235 y: 5.2089